runtime: nodejs
env: flex

env_variables:
  USERNAME: dandyuser
  PASSWORD: test
  DATABASE_NAME: parking
  CONNECTION_NAME: dandy-293601:northamerica-northeast1:dandydb
  DIALECT: mysql
  NODE_ENV: production

beta_settings:
  cloud_sql_instances: dandy-293601:northamerica-northeast1:dandydb