runtime: nodejs
env: flex

env_variables:
  USERNAME: dandyuser
  PASSWORD: test
  DATABASE_NAME: parking
  CONNECTION_NAME: dandyv2:us-central1:dandydb
  DIALECT: mysql
  NODE_ENV: production

beta_settings:
  cloud_sql_instances: dandyv2:us-central1:dandydb